[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "https://ansarmehmood.com/*"
  to = "https://ansarmehmood.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.ansarmehmood.dev/*"
  to = "https://ansarmehmood.dev/:splat"
  status = 301
  force = true

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"